### ISSUE TITLE
Use of /app code in migrations 

### ISSUE THREAD

**Issue by peterhassler** [simpliflow/Rails-Styleguide#6]
https://github.com/simpliflow/Rails-Styleguide#define-model-class-migrations

In FCS, we don't care about migrations accessing stable apis in /app code. Migrations usually live for 1-2 months, until the next deployment and after then, they can become defect because there is no need to maintain them.
This works because all of our live systems get updated as soon as a new version gets released (this way, migrations are usually tested eg 3.8 -> 3.9). 

This will get us into problems as soon as:
- Live systems start skipping versions: eg upgrade 3.5 to 4.5: migrations added in 3.6 may be defect because the app code they use changed

Impact: Unable to update live system because migrations crash. App will mostly need a hotfix that needs to be deployed again.

We should think about how to handle this issue in future.

**Comment by tomgong** [comment]
For me this is only a potential problem and should never happen because we should always deploy near to the creation of the migration. Show me a real use case (and I don't mean updating dev databases) in the past where this was an issue. 
Of course, the migrations should be written with "best effort" to keep compatibility to the /app code base.

**Comment by peterhassler** [comment]
Additional information about this problem: We use a 'clean dump' for our quick deploy job, so that we don't always need to fetch the whole dump from staging. This dump gets outdated over time. The less we invest in 'non-app-dependent-migrations', the more we have to update clean dump manually.

**Comment by peterhassler** [comment]
> We use a 'clean dump' for our quick deploy job, so that we don't always need to fetch the whole dump from staging. 
> This dump gets outdated over time.

The dump does not get outdated anymore. It gets migrated everytime master changes.

This fact makes general rules how to handle migrations with dependencies unnecessary. I will remove the whole section.

**Comment by peterhassler** [comment]
resume discussion in PR
